# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/toor/ipwndfu_rewrite_c

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/toor/ipwndfu_rewrite_c

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/toor/ipwndfu_rewrite_c/CMakeFiles /home/toor/ipwndfu_rewrite_c/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/toor/ipwndfu_rewrite_c/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named checkm8_libusb

# Build rule for target.
checkm8_libusb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 checkm8_libusb
.PHONY : checkm8_libusb

# fast build rule for target.
checkm8_libusb/fast:
	$(MAKE) -f CMakeFiles/checkm8_libusb.dir/build.make CMakeFiles/checkm8_libusb.dir/build
.PHONY : checkm8_libusb/fast

#=============================================================================
# Target rules for targets named checkm8_remote

# Build rule for target.
checkm8_remote: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 checkm8_remote
.PHONY : checkm8_remote

# fast build rule for target.
checkm8_remote/fast:
	$(MAKE) -f checkm8_remote/CMakeFiles/checkm8_remote.dir/build.make checkm8_remote/CMakeFiles/checkm8_remote.dir/build
.PHONY : checkm8_remote/fast

#=============================================================================
# Target rules for targets named payload_sysreg

# Build rule for target.
payload_sysreg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 payload_sysreg
.PHONY : payload_sysreg

# fast build rule for target.
payload_sysreg/fast:
	$(MAKE) -f checkm8_payloads/CMakeFiles/payload_sysreg.dir/build.make checkm8_payloads/CMakeFiles/payload_sysreg.dir/build
.PHONY : payload_sysreg/fast

#=============================================================================
# Target rules for targets named payload_sync

# Build rule for target.
payload_sync: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 payload_sync
.PHONY : payload_sync

# fast build rule for target.
payload_sync/fast:
	$(MAKE) -f checkm8_payloads/CMakeFiles/payload_sync.dir/build.make checkm8_payloads/CMakeFiles/payload_sync.dir/build
.PHONY : payload_sync/fast

#=============================================================================
# Target rules for targets named payload_aes

# Build rule for target.
payload_aes: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 payload_aes
.PHONY : payload_aes

# fast build rule for target.
payload_aes/fast:
	$(MAKE) -f checkm8_payloads/CMakeFiles/payload_aes.dir/build.make checkm8_payloads/CMakeFiles/payload_aes.dir/build
.PHONY : payload_aes/fast

checkm8_libusb/src/core.o: checkm8_libusb/src/core.c.o

.PHONY : checkm8_libusb/src/core.o

# target to build an object file
checkm8_libusb/src/core.c.o:
	$(MAKE) -f CMakeFiles/checkm8_libusb.dir/build.make CMakeFiles/checkm8_libusb.dir/checkm8_libusb/src/core.c.o
.PHONY : checkm8_libusb/src/core.c.o

checkm8_libusb/src/core.i: checkm8_libusb/src/core.c.i

.PHONY : checkm8_libusb/src/core.i

# target to preprocess a source file
checkm8_libusb/src/core.c.i:
	$(MAKE) -f CMakeFiles/checkm8_libusb.dir/build.make CMakeFiles/checkm8_libusb.dir/checkm8_libusb/src/core.c.i
.PHONY : checkm8_libusb/src/core.c.i

checkm8_libusb/src/core.s: checkm8_libusb/src/core.c.s

.PHONY : checkm8_libusb/src/core.s

# target to generate assembly for a file
checkm8_libusb/src/core.c.s:
	$(MAKE) -f CMakeFiles/checkm8_libusb.dir/build.make CMakeFiles/checkm8_libusb.dir/checkm8_libusb/src/core.c.s
.PHONY : checkm8_libusb/src/core.c.s

checkm8_libusb/src/descriptor.o: checkm8_libusb/src/descriptor.c.o

.PHONY : checkm8_libusb/src/descriptor.o

# target to build an object file
checkm8_libusb/src/descriptor.c.o:
	$(MAKE) -f CMakeFiles/checkm8_libusb.dir/build.make CMakeFiles/checkm8_libusb.dir/checkm8_libusb/src/descriptor.c.o
.PHONY : checkm8_libusb/src/descriptor.c.o

checkm8_libusb/src/descriptor.i: checkm8_libusb/src/descriptor.c.i

.PHONY : checkm8_libusb/src/descriptor.i

# target to preprocess a source file
checkm8_libusb/src/descriptor.c.i:
	$(MAKE) -f CMakeFiles/checkm8_libusb.dir/build.make CMakeFiles/checkm8_libusb.dir/checkm8_libusb/src/descriptor.c.i
.PHONY : checkm8_libusb/src/descriptor.c.i

checkm8_libusb/src/descriptor.s: checkm8_libusb/src/descriptor.c.s

.PHONY : checkm8_libusb/src/descriptor.s

# target to generate assembly for a file
checkm8_libusb/src/descriptor.c.s:
	$(MAKE) -f CMakeFiles/checkm8_libusb.dir/build.make CMakeFiles/checkm8_libusb.dir/checkm8_libusb/src/descriptor.c.s
.PHONY : checkm8_libusb/src/descriptor.c.s

checkm8_libusb/src/hotplug.o: checkm8_libusb/src/hotplug.c.o

.PHONY : checkm8_libusb/src/hotplug.o

# target to build an object file
checkm8_libusb/src/hotplug.c.o:
	$(MAKE) -f CMakeFiles/checkm8_libusb.dir/build.make CMakeFiles/checkm8_libusb.dir/checkm8_libusb/src/hotplug.c.o
.PHONY : checkm8_libusb/src/hotplug.c.o

checkm8_libusb/src/hotplug.i: checkm8_libusb/src/hotplug.c.i

.PHONY : checkm8_libusb/src/hotplug.i

# target to preprocess a source file
checkm8_libusb/src/hotplug.c.i:
	$(MAKE) -f CMakeFiles/checkm8_libusb.dir/build.make CMakeFiles/checkm8_libusb.dir/checkm8_libusb/src/hotplug.c.i
.PHONY : checkm8_libusb/src/hotplug.c.i

checkm8_libusb/src/hotplug.s: checkm8_libusb/src/hotplug.c.s

.PHONY : checkm8_libusb/src/hotplug.s

# target to generate assembly for a file
checkm8_libusb/src/hotplug.c.s:
	$(MAKE) -f CMakeFiles/checkm8_libusb.dir/build.make CMakeFiles/checkm8_libusb.dir/checkm8_libusb/src/hotplug.c.s
.PHONY : checkm8_libusb/src/hotplug.c.s

checkm8_libusb/src/io.o: checkm8_libusb/src/io.c.o

.PHONY : checkm8_libusb/src/io.o

# target to build an object file
checkm8_libusb/src/io.c.o:
	$(MAKE) -f CMakeFiles/checkm8_libusb.dir/build.make CMakeFiles/checkm8_libusb.dir/checkm8_libusb/src/io.c.o
.PHONY : checkm8_libusb/src/io.c.o

checkm8_libusb/src/io.i: checkm8_libusb/src/io.c.i

.PHONY : checkm8_libusb/src/io.i

# target to preprocess a source file
checkm8_libusb/src/io.c.i:
	$(MAKE) -f CMakeFiles/checkm8_libusb.dir/build.make CMakeFiles/checkm8_libusb.dir/checkm8_libusb/src/io.c.i
.PHONY : checkm8_libusb/src/io.c.i

checkm8_libusb/src/io.s: checkm8_libusb/src/io.c.s

.PHONY : checkm8_libusb/src/io.s

# target to generate assembly for a file
checkm8_libusb/src/io.c.s:
	$(MAKE) -f CMakeFiles/checkm8_libusb.dir/build.make CMakeFiles/checkm8_libusb.dir/checkm8_libusb/src/io.c.s
.PHONY : checkm8_libusb/src/io.c.s

checkm8_libusb/src/os/linux_netlink.o: checkm8_libusb/src/os/linux_netlink.c.o

.PHONY : checkm8_libusb/src/os/linux_netlink.o

# target to build an object file
checkm8_libusb/src/os/linux_netlink.c.o:
	$(MAKE) -f CMakeFiles/checkm8_libusb.dir/build.make CMakeFiles/checkm8_libusb.dir/checkm8_libusb/src/os/linux_netlink.c.o
.PHONY : checkm8_libusb/src/os/linux_netlink.c.o

checkm8_libusb/src/os/linux_netlink.i: checkm8_libusb/src/os/linux_netlink.c.i

.PHONY : checkm8_libusb/src/os/linux_netlink.i

# target to preprocess a source file
checkm8_libusb/src/os/linux_netlink.c.i:
	$(MAKE) -f CMakeFiles/checkm8_libusb.dir/build.make CMakeFiles/checkm8_libusb.dir/checkm8_libusb/src/os/linux_netlink.c.i
.PHONY : checkm8_libusb/src/os/linux_netlink.c.i

checkm8_libusb/src/os/linux_netlink.s: checkm8_libusb/src/os/linux_netlink.c.s

.PHONY : checkm8_libusb/src/os/linux_netlink.s

# target to generate assembly for a file
checkm8_libusb/src/os/linux_netlink.c.s:
	$(MAKE) -f CMakeFiles/checkm8_libusb.dir/build.make CMakeFiles/checkm8_libusb.dir/checkm8_libusb/src/os/linux_netlink.c.s
.PHONY : checkm8_libusb/src/os/linux_netlink.c.s

checkm8_libusb/src/os/linux_udev.o: checkm8_libusb/src/os/linux_udev.c.o

.PHONY : checkm8_libusb/src/os/linux_udev.o

# target to build an object file
checkm8_libusb/src/os/linux_udev.c.o:
	$(MAKE) -f CMakeFiles/checkm8_libusb.dir/build.make CMakeFiles/checkm8_libusb.dir/checkm8_libusb/src/os/linux_udev.c.o
.PHONY : checkm8_libusb/src/os/linux_udev.c.o

checkm8_libusb/src/os/linux_udev.i: checkm8_libusb/src/os/linux_udev.c.i

.PHONY : checkm8_libusb/src/os/linux_udev.i

# target to preprocess a source file
checkm8_libusb/src/os/linux_udev.c.i:
	$(MAKE) -f CMakeFiles/checkm8_libusb.dir/build.make CMakeFiles/checkm8_libusb.dir/checkm8_libusb/src/os/linux_udev.c.i
.PHONY : checkm8_libusb/src/os/linux_udev.c.i

checkm8_libusb/src/os/linux_udev.s: checkm8_libusb/src/os/linux_udev.c.s

.PHONY : checkm8_libusb/src/os/linux_udev.s

# target to generate assembly for a file
checkm8_libusb/src/os/linux_udev.c.s:
	$(MAKE) -f CMakeFiles/checkm8_libusb.dir/build.make CMakeFiles/checkm8_libusb.dir/checkm8_libusb/src/os/linux_udev.c.s
.PHONY : checkm8_libusb/src/os/linux_udev.c.s

checkm8_libusb/src/os/linux_usbfs.o: checkm8_libusb/src/os/linux_usbfs.c.o

.PHONY : checkm8_libusb/src/os/linux_usbfs.o

# target to build an object file
checkm8_libusb/src/os/linux_usbfs.c.o:
	$(MAKE) -f CMakeFiles/checkm8_libusb.dir/build.make CMakeFiles/checkm8_libusb.dir/checkm8_libusb/src/os/linux_usbfs.c.o
.PHONY : checkm8_libusb/src/os/linux_usbfs.c.o

checkm8_libusb/src/os/linux_usbfs.i: checkm8_libusb/src/os/linux_usbfs.c.i

.PHONY : checkm8_libusb/src/os/linux_usbfs.i

# target to preprocess a source file
checkm8_libusb/src/os/linux_usbfs.c.i:
	$(MAKE) -f CMakeFiles/checkm8_libusb.dir/build.make CMakeFiles/checkm8_libusb.dir/checkm8_libusb/src/os/linux_usbfs.c.i
.PHONY : checkm8_libusb/src/os/linux_usbfs.c.i

checkm8_libusb/src/os/linux_usbfs.s: checkm8_libusb/src/os/linux_usbfs.c.s

.PHONY : checkm8_libusb/src/os/linux_usbfs.s

# target to generate assembly for a file
checkm8_libusb/src/os/linux_usbfs.c.s:
	$(MAKE) -f CMakeFiles/checkm8_libusb.dir/build.make CMakeFiles/checkm8_libusb.dir/checkm8_libusb/src/os/linux_usbfs.c.s
.PHONY : checkm8_libusb/src/os/linux_usbfs.c.s

checkm8_libusb/src/os/poll_posix.o: checkm8_libusb/src/os/poll_posix.c.o

.PHONY : checkm8_libusb/src/os/poll_posix.o

# target to build an object file
checkm8_libusb/src/os/poll_posix.c.o:
	$(MAKE) -f CMakeFiles/checkm8_libusb.dir/build.make CMakeFiles/checkm8_libusb.dir/checkm8_libusb/src/os/poll_posix.c.o
.PHONY : checkm8_libusb/src/os/poll_posix.c.o

checkm8_libusb/src/os/poll_posix.i: checkm8_libusb/src/os/poll_posix.c.i

.PHONY : checkm8_libusb/src/os/poll_posix.i

# target to preprocess a source file
checkm8_libusb/src/os/poll_posix.c.i:
	$(MAKE) -f CMakeFiles/checkm8_libusb.dir/build.make CMakeFiles/checkm8_libusb.dir/checkm8_libusb/src/os/poll_posix.c.i
.PHONY : checkm8_libusb/src/os/poll_posix.c.i

checkm8_libusb/src/os/poll_posix.s: checkm8_libusb/src/os/poll_posix.c.s

.PHONY : checkm8_libusb/src/os/poll_posix.s

# target to generate assembly for a file
checkm8_libusb/src/os/poll_posix.c.s:
	$(MAKE) -f CMakeFiles/checkm8_libusb.dir/build.make CMakeFiles/checkm8_libusb.dir/checkm8_libusb/src/os/poll_posix.c.s
.PHONY : checkm8_libusb/src/os/poll_posix.c.s

checkm8_libusb/src/os/threads_posix.o: checkm8_libusb/src/os/threads_posix.c.o

.PHONY : checkm8_libusb/src/os/threads_posix.o

# target to build an object file
checkm8_libusb/src/os/threads_posix.c.o:
	$(MAKE) -f CMakeFiles/checkm8_libusb.dir/build.make CMakeFiles/checkm8_libusb.dir/checkm8_libusb/src/os/threads_posix.c.o
.PHONY : checkm8_libusb/src/os/threads_posix.c.o

checkm8_libusb/src/os/threads_posix.i: checkm8_libusb/src/os/threads_posix.c.i

.PHONY : checkm8_libusb/src/os/threads_posix.i

# target to preprocess a source file
checkm8_libusb/src/os/threads_posix.c.i:
	$(MAKE) -f CMakeFiles/checkm8_libusb.dir/build.make CMakeFiles/checkm8_libusb.dir/checkm8_libusb/src/os/threads_posix.c.i
.PHONY : checkm8_libusb/src/os/threads_posix.c.i

checkm8_libusb/src/os/threads_posix.s: checkm8_libusb/src/os/threads_posix.c.s

.PHONY : checkm8_libusb/src/os/threads_posix.s

# target to generate assembly for a file
checkm8_libusb/src/os/threads_posix.c.s:
	$(MAKE) -f CMakeFiles/checkm8_libusb.dir/build.make CMakeFiles/checkm8_libusb.dir/checkm8_libusb/src/os/threads_posix.c.s
.PHONY : checkm8_libusb/src/os/threads_posix.c.s

checkm8_libusb/src/strerror.o: checkm8_libusb/src/strerror.c.o

.PHONY : checkm8_libusb/src/strerror.o

# target to build an object file
checkm8_libusb/src/strerror.c.o:
	$(MAKE) -f CMakeFiles/checkm8_libusb.dir/build.make CMakeFiles/checkm8_libusb.dir/checkm8_libusb/src/strerror.c.o
.PHONY : checkm8_libusb/src/strerror.c.o

checkm8_libusb/src/strerror.i: checkm8_libusb/src/strerror.c.i

.PHONY : checkm8_libusb/src/strerror.i

# target to preprocess a source file
checkm8_libusb/src/strerror.c.i:
	$(MAKE) -f CMakeFiles/checkm8_libusb.dir/build.make CMakeFiles/checkm8_libusb.dir/checkm8_libusb/src/strerror.c.i
.PHONY : checkm8_libusb/src/strerror.c.i

checkm8_libusb/src/strerror.s: checkm8_libusb/src/strerror.c.s

.PHONY : checkm8_libusb/src/strerror.s

# target to generate assembly for a file
checkm8_libusb/src/strerror.c.s:
	$(MAKE) -f CMakeFiles/checkm8_libusb.dir/build.make CMakeFiles/checkm8_libusb.dir/checkm8_libusb/src/strerror.c.s
.PHONY : checkm8_libusb/src/strerror.c.s

checkm8_libusb/src/sync.o: checkm8_libusb/src/sync.c.o

.PHONY : checkm8_libusb/src/sync.o

# target to build an object file
checkm8_libusb/src/sync.c.o:
	$(MAKE) -f CMakeFiles/checkm8_libusb.dir/build.make CMakeFiles/checkm8_libusb.dir/checkm8_libusb/src/sync.c.o
.PHONY : checkm8_libusb/src/sync.c.o

checkm8_libusb/src/sync.i: checkm8_libusb/src/sync.c.i

.PHONY : checkm8_libusb/src/sync.i

# target to preprocess a source file
checkm8_libusb/src/sync.c.i:
	$(MAKE) -f CMakeFiles/checkm8_libusb.dir/build.make CMakeFiles/checkm8_libusb.dir/checkm8_libusb/src/sync.c.i
.PHONY : checkm8_libusb/src/sync.c.i

checkm8_libusb/src/sync.s: checkm8_libusb/src/sync.c.s

.PHONY : checkm8_libusb/src/sync.s

# target to generate assembly for a file
checkm8_libusb/src/sync.c.s:
	$(MAKE) -f CMakeFiles/checkm8_libusb.dir/build.make CMakeFiles/checkm8_libusb.dir/checkm8_libusb/src/sync.c.s
.PHONY : checkm8_libusb/src/sync.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... checkm8_libusb"
	@echo "... edit_cache"
	@echo "... checkm8_remote"
	@echo "... payload_sysreg"
	@echo "... payload_sync"
	@echo "... payload_aes"
	@echo "... checkm8_libusb/src/core.o"
	@echo "... checkm8_libusb/src/core.i"
	@echo "... checkm8_libusb/src/core.s"
	@echo "... checkm8_libusb/src/descriptor.o"
	@echo "... checkm8_libusb/src/descriptor.i"
	@echo "... checkm8_libusb/src/descriptor.s"
	@echo "... checkm8_libusb/src/hotplug.o"
	@echo "... checkm8_libusb/src/hotplug.i"
	@echo "... checkm8_libusb/src/hotplug.s"
	@echo "... checkm8_libusb/src/io.o"
	@echo "... checkm8_libusb/src/io.i"
	@echo "... checkm8_libusb/src/io.s"
	@echo "... checkm8_libusb/src/os/linux_netlink.o"
	@echo "... checkm8_libusb/src/os/linux_netlink.i"
	@echo "... checkm8_libusb/src/os/linux_netlink.s"
	@echo "... checkm8_libusb/src/os/linux_udev.o"
	@echo "... checkm8_libusb/src/os/linux_udev.i"
	@echo "... checkm8_libusb/src/os/linux_udev.s"
	@echo "... checkm8_libusb/src/os/linux_usbfs.o"
	@echo "... checkm8_libusb/src/os/linux_usbfs.i"
	@echo "... checkm8_libusb/src/os/linux_usbfs.s"
	@echo "... checkm8_libusb/src/os/poll_posix.o"
	@echo "... checkm8_libusb/src/os/poll_posix.i"
	@echo "... checkm8_libusb/src/os/poll_posix.s"
	@echo "... checkm8_libusb/src/os/threads_posix.o"
	@echo "... checkm8_libusb/src/os/threads_posix.i"
	@echo "... checkm8_libusb/src/os/threads_posix.s"
	@echo "... checkm8_libusb/src/strerror.o"
	@echo "... checkm8_libusb/src/strerror.i"
	@echo "... checkm8_libusb/src/strerror.s"
	@echo "... checkm8_libusb/src/sync.o"
	@echo "... checkm8_libusb/src/sync.i"
	@echo "... checkm8_libusb/src/sync.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

