#ifndef IPWNDFU_REWRITE_C_BRFUNC_AES_H
#define IPWNDFU_REWRITE_C_BRFUNC_AES_H

#include "brfunc_common.h"

#define AES_HW_CRYPTO_CMD           ((BOOTROM_FUNC) ADDR_AES_HW_CRYPTO_CMD)

#define CREATE_KEY_COMMAND          ((BOOTROM_FUNC) ADDR_CREATE_KEY_COMMAND)
#define PUSH_COMMAND_KEY            ((BOOTROM_FUNC) ADDR_PUSH_COMMAND_KEY)
#define PUSH_COMMAND_IV             ((BOOTROM_FUNC) ADDR_PUSH_COMMAND_IV)
#define PUSH_COMMAND_DATA           ((BOOTROM_FUNC) ADDR_PUSH_COMMAND_DATA)
#define PUSH_COMMAND_FLAG           ((BOOTROM_FUNC) ADDR_PUSH_COMMAND_FLAG)
#define WAIT_FOR_COMMAND_FLAG       ((BOOTROM_FUNC) ADDR_WAIT_FOR_COMMAND)

#define rAES_INT_STATUS             (long *) ADDR_AES_CONTROL
#define rAES_CONTROL                (long *) ADDR_AES_STATUS

#endif //IPWNDFU_REWRITE_C_BRFUNC_AES_H
