#ifndef IPWNDFU_REWRITE_C_BRFUNC_SEP_H
#define IPWNDFU_REWRITE_C_BRFUNC_SEP_H

#include "brfunc_common.h"

#define DPA_SEEDED                  ((BOOTROM_FUNC) ADDR_DPA_SEEDED)
#define SEP_CREATE_SEND_DPA_MESSAGE ((BOOTROM_FUNC) ADDR_SEND_DPA_MESSAGE)

#endif //IPWNDFU_REWRITE_C_BRFUNC_SEP_H
